spring:
  application:
    name: statemachine-demo
  datasource:
    url: jdbc:mysql://localhost:3306/statemachine?characterEncoding=utf-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8701
  servlet:
    context-path: /statemachine-demo

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    # 只在控制台打印sql，不输出到日志中
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl